START_TERMS = [
    'cut to', 'flash to', 'short time cut to', 'close-up of monitor', 'insert flash of', 
    'quick flashback to', 'top view down', 'cue song', 'flashback to', 'scope view', 'camera '
    'quick flash to', 'quick flash of', 'quick cgi pov to', 'quick cgi pov of', 'quick flashback of', 
    'quick cgi pov', 'quick cgi to', 'white flash to', 'cut back to', 'close-up', 'quick flashes of', 
    '[cu', 'cu', 'ct loc', 'close up of', 'quick cgi efx', 'various cuts of', 'flash to white',
    'quick cgi flash of', 'quick cgi of', 'top half', 'close-up of', 'fade to', 'quick cgi flashback to',
    'quick visualization of', 'slow on', 'cgi efx', 'dissolve to time stamp reading', 'dissolve to', 
    'fast forward', 'flashback', 'quick flashback', 'quick virtual pov of', 'scenes of', 'various dissolves of', 
    'camera cuts to', 'camera holds on the timer', 'camera pov of', 'camera view', 'close up', 'fade in to', 'fade in', 
    'flashback to', 'open on', 'quick cgi flash to', 'quick cgi visual image', 'quick flash close-up of the item on the list', 
    'quick flashbacks of', 'quick pov of', 'slow motion', 'a camera flash to', '[scene from', 'top camera view',
    'enhanced camera view', 'hard cut to', 'fish above door', 'night vision green', 'various flashes of', 'cgi zoom',
    'music', 'lyric', 'cgi', 'pull back', 'song', 'on monitor', 'insert'
]

NON_HUMAN_SPEAKERS = [
    'NIGHT VISION GREEN', 'FISH ABOVE DOOR', 
    'LAS VEGAS, NV89109', 'DOB', 'LAS VEGAS, NV', 'LAS VEGAS NV', 
    'Sample Name', 'Misc Info', 'Vial Number', 'Findings', 'Age', 'CAR', 'NAME', 'ADDRESS', 'STATUTE',
    'HAIR', 'RACE', 'WEIGHT', 'AGE', 'INSERT', 'SEX', 'ITEM', 'TO', 
    'EXPIRES', 'BIRTHDATE', 'MISSING', 'EYES', 'HEIGHT', 'ARREST',
    'Address', 'VIOL', 'DOC#', 'FROM', 'From', 'To', 'Date', 'TYPE',
    'TOTAL', '[SCOPE VIEW]', '[GILBERT GOTTFRIED]', 'SUSPECT', 'DATE', 'Name', 'HGT',
    'Location', 'HENDERSON, NV', 'TIME', 'CONVICTIONS', 'SSN', 
    'DISPOSITIONS', 'VARIOUS FLASHES OF', 'CGI ZOOM', 'Phone', 'Subject', 'R#', 
    'EXPIRATION DATE', 'OCCUPATION', 'SUBTOTAL', 'Full Name', 'Birth Date', 'PLEDGE', 
    'CAMERA', 'ATTN', 'PAYING CUSTOMER', 'LIC', 'LVPD', 'HI-DEF',
    'FISH ABOVE DOOR', 'Findings', 'MUSIC', '\\[b\\]Lyric\\[\\/b\\]', 'LVMP', 'CASE NO.', 
    'DEPT. NO. F DOCKET', 'Report Date', 'EMPLOYMENT', 'Sent', 'Hair', 'ARTICLE', 
    'WHERE THIS ARTICLE WAS FOUND', 'Match Found', 'Case ID', 'HT', 'Flash Radius', 'TAX', 
    'ACCOUNT NUMBER', 'METER ADDRESS', 'BILLING CYCLE', 'DAYS OF SERVICE', 'BILL TYPE', 'Article', 
    'LOS ANGELES, CA', 'City', 'ENDANGERED RUNAWAY', 'Race', 'PHONE NO', 'REFILLS', 'USE BY', 'ALIAS', 
    'DATE AND TIME OF RECOVERY', 'SEALED BY', 'STOP', 'MULTIPLE', '([NIGHT]', 'YEAR SENTENCE', 
    'CNT', 'PACKAGE', 'PATTERN', 'CLASS', 'DISPOSITION', 'CASE MODIFIED ON', 'POV', 'FILE DATE', 'CASE LVPD', 
    'LVPD ROUTING', 'SONG', 'PULL BACK', 'CGI', 'ON MONITOR', 'REVEAL', 'T', 'C', 'By', 'IN',
    'SIGN', 'Case Reported', 'Decedent Data Name', 'Sex', 'Destination', 'Pnt', 'Time Admitted', 'Rx No', 
    'DISCARD AFTER', 'REMARK/OTHER', 'SUSP', 'SERV-TYPE', 'FILE# MAILED', 'VEH LIC#029836274', 'THREE MORE', 
    'DATE PREPARED', 'TIME PREPARED', 'Staute', 'MPH', 'Work Location', 'ID#', 'R# N6479', 'CC/4', 'H??O',
    'GP/2', 'Missing', 'RESULTS', 'Control ID', 'Print', 'Class Score', 'Database', 'Case', 'Class', 'Weight', 
    'EMER. PHONE', 'A.D.A.', 'Served', 'SECURE DATA Name', 'RSTR', 'PAY THE SUM OF', 'REFERENCE NO.', 'LOCATION', 
    'VERIFY', 'Loc', 'GRIS. GOT THE', 'Type', 'Description', 'Code', 'ID TYPE', 'MCX', 'CARD#', 'ANGLE ON', 
    'SUZANNA', 'PLUSHIE', 'LAS VEGAS, NEVADA', 'BPA', 'EYEWITNESS NEWS', 'TAKES TOP PRIORITY', 'NORMAL SALE', 
    'Searched', 'BILLING ADDRESS', 'PAYMENT DUE DATE', 'MESQUITE, NV', 'PENNY', 'STORE', 'W. SHIRT', 'PANTS', 
    'SALE', 'ISSUED', 'EXPIRE', 'ARTISTIC MIME', 'DET. VARTANN', 'Criminal Records', 'NEIS', 'ATM', 'TALLAHASSEE, FL', 
    'HOW CAN', "Owner's Signature", 'Telephone', 'CALLED NUMBER', 'DURATION', "WINNER'S Name", 'DOB/', 'CHARGES', 
    'Human Genetics', 'CAR RENTAL', 'LICENSE', 'EYES BL HEIGHT', 'HAIR BLN WEIGHT', 'ID NUMBER', 'ENDANGERED MISSING', 
    'Occupation', 'Status', 'Hgt', 'SEARCH DATE',  'INGREDIENTS', 'BOTOX INJECTIONS-', 'Cat. No.', 'FALL', 'NO.', 
    'Case Number', 'TOWER EAST', 'TYPE VEHICLE USE', 'AUTOMOBILE', 'NOMBRE', 'PECHA', 'MATCHBOOK', 'VOLUME', 'NUMBER',
    'IN CUSTODY', 'FADE OUT', 'COCAINE', 'TOP', 'SATURDAY DECEMBER', 'Title Match Fight', 'A-T.', 'EXTREME CLOSE-UP', 
    'ONLY', 'BURN UNIT', 'S. SIDLE', 'LPD', 'AKA', 'COLT', 'SOLD SEPT.', 'CASE REPORT', 'LOGGED', 'LAPD, SERVICE', 
    'EVIDENCE RETRIEVED', 'CASE#', 'LAPD', 'DIAGNOSIS', 'MULTIPLE RITUAL', 'TIME ADMITTED', 'SUBJECT', "JEFF SIMON'S POV", 
    'CALL', 'RESTRICTED', 'SEMTEX', 'COURT', 'GROOVE', 'COMPANY NUMBER', 'COMPANY', 'POLICY NUMBER', 'EFFECTIVE DATE', 
    'MAKE', 'YEAR', 'LICENSE PLATE', 'VIN#', 'FROM EVIDENCE ITEM', 'WITH GMC PRODUCTS', 'SEDAN SERVICE', 'NOTES', 
    'ALIASES', 'IC#', 'ISSN', 'FILE PRINT', 'SUNSET HALL,', 'LAS VEGAS, NY', 'Relieves', 'RED', 'Fax', 
    'IN PRIZE MONEY', 'Offense', 'NRS', 'Domain Name', 'IP Address', 'CASE NUMBER', 'CASE CREATED', 'REQUESTED ANALYSIS', 
    'DEPARTMENT', 'SCENE LOCATION', 'ADJUCATION', 'CASE CREATED ON', 'BIN', 'DRAWER', 'Color Type', 'NUMBER ENTERED', 
    'VIN', 'AMOUNT', 'DROOVE', "Resident's Name", 'Company', 'CRIMINAL HISTORY', 'STATUE', 'NAME OF SUBJECT', 'OFFENSE', 
    'DATE OF INCIDENT', 'P.M.', 'Birthdate', 'Social Security', 'License Plate', 'THE', 'SPEER', 'ITEM STOLEN', 
    'SUSPECT INFO', 'MISCELLANEOUS', 'NOTE', 'ENTER SERIAL NUMBER', 'CITY STATE', 'ECU', 'DIAZEPAM', 'Refills', 
    'GREG FLASHBACK TO', 'ROUTING CODE', 'CASE', 'AMERICAN TOURIST', 'TAKE', 'EAGLE, NV', 'MESSAGE', 'Pigman', 
    'DEAR MR. GRISSOM,', 'LUNCH MEETING', 'CAMERA ZOOMS OUT', 'SEATTLE WA', 'POPULATION', 'EYE COLOR', 
    'IDENTIFYING MARKS', 'HAIR COLOR', 'CONTENTS', 'DATE FILED', 'KEY WORDS', 'ACQUIRED', 'INSTRUMENT', 'RECOVERED BY', 
    'BADGE', "KEPPLER'S POV", 'LOST', 'UNABLE TO DETECT', 'BLUE SIREN MOTEL', 'LAS VEGAS, NB', 'YOU WERE WRONG', 
    'PHOTO FREEZE-FRAME', 'FEBRUARY', 'AUGUST', 'JUNE', 'SEN', 'SEN.', 'FWD', "WENDY'S HERE", 'FILE', 'BFT', 'APRIL', 
    'GOLD LEVEL MEMBERS', 'UNHURRIED SINCE', 'COLOR HAIR', 'COLOR EYES', 'GOT', 'Received', 'FREEZE FRAME', 'FRINE ST.', 
    'CASE FILE NO. LVPD', 'RED MUSTANG', 'RED ROCK CANYON', 'SUNRISE MOUNTAIN', 'LAKE MEAD', 'LAS VEGAS DUNES', 
    'SPRING MOUNTAIN', 'MUSIC STARTS', 'HOLD', "WARRICK'S POV", 'COMING SOON SPRING', 'ECLIPSE HOTEL', 'STATE', 
    'OTHER POV', 'XCU', 'PUSH FORWARD', 'INFORMATION SHEET', 'CGI OF', 'PHOTOS', 'WITHOUT', 'ON CHAIR', 'ON HODGES', 
    'CGI ZOOM TO', 'CGI THROUGH', 'CSI', 'MOUNTING CODE', 'SERIES', 'DISTORTED IMAGES', 'INSERT FLASHES OF', 'ROOM NO', 
    'ROOM TYPE', 'ROOM PREFERENCES', 'PAYMENT', 'CARD NO', 'CLOSE ON', 'Time', 'SEND', 'NV', 'PLACE'
]

IGNORE_SPEAKERS = [
    'sound', 'sound cue', 'lyric', 'lyrics', 'cue sound', 'cgi.', 'cgi', 'room',
    'cgi pov', 'solved', '500', 'chemlab', 'fp', 'a little white', 'al', 'observation room', 
    'one of our own', 'whiteboard', 'id', 'voice', 'narrator', 'night', 'als', 'suv', 'dna', 
    'day', 'a', 'cd', 'v', 'id', 'jr', 'g*n', 'pm', 'dvd', 'radio', 'sr', 'dmv', 'pov', 'iv', 
    'cpr', 'thd', 'am', 'i.d', 'no match', 'earlier', 'er', 'nv', 'photo', 'dna lab', 'far', 
    'night] a', 'second', '1x01', 'age', 'co2', 'cps', 'csi', 'det', 'eye', 'hallway', 'happy', 
    'height', 'hot dog vendor', 'hotel room', 'iab', 'int. club', 'k*ll', 'kitchen', 'las vegas', 
    'logos', 'party', 'tv', 'vip', 'zoom', '1x08', 'asl', 'atv', 'b', 'baby', 'bar', 'bedroom closet', 
    'bitch', 'brn', 'crime', 'cu', 'da', 'date', 'day] a', 'directly', 'elevator', 'everyone', 
    'evidence', 'exit', 'ext', 'gg', 'head', 'headshot', 'highball', 'house', 'io', 'match', 'mr', 
    'pj', 's&s', 'sexy', 'all', 'atf', 'b\\]lyric\\[\\', 'bc', 'bf', 'bmw', 'cgi', 'cgi-pov', 
    'detail', 'ds jl', 'evo\'d', 'first', 'front', 'gmc', 'gps', 'hall', 'i.v', '2-f', 'int', 
    'u.s.a', '', '\\[b\\]lyric\\[\\', 'a.m.', 'zooms', 'court: nam:01', 'pda', 'nov', 'live', 
    'l-a-t', 'feet', 'do not open', 'caprice unlimited', 'club', 'crowd', 'apapsp', 'apr', 'apt', 
    'arcb-421', '\\[b\\]lyric\\[\\/b\\', '\\[b\\]Lyric\\[\\', 'b\\', 'computer', 'computer screen 1', 
    'computer screen 2', 'computer screen 3', 'computer screen 4', 'computer screen 5', 'e-mail', 
    'box 1', 'box 2', 'box 3',
]

SPECIAL_CHARS = [
    'narrator', 'overhead', 'voice', 'voices', 'sound', 'cgi', 'cgi.', 'cgi-pov', 
    'radio', 'radios', 'recordings', 'recording', 'music', 'lyric', 'lyrics', 
    'b\\]lyric\\[\\', '\\[b\\]lyric\\[\\', '\\[b\\]lyric\\[\\/b\\', '\\[b\\]Lyric\\[\\', 
    'b\\', 'computer', 'screen', 'e-mail', 'int', 'dna lab', 'dna', 'chemlab',
    'whiteboard', 'scope', 'view', 'lvpd', 'report', 'box', 'clipboard'
]